<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['name' => 'Afghanistan', 'code' => 'AF', 'iso_code' => 'AFG', 'phone_code' => '93'],
            ['name' => 'Albania', 'code' => 'AL', 'iso_code' => 'ALB', 'phone_code' => '355'],
            ['name' => 'Algeria', 'code' => 'DZ', 'iso_code' => 'DZA', 'phone_code' => '213'],
            ['name' => 'American Samoa', 'code' => 'AS', 'iso_code' => 'ASM', 'phone_code' => '1684'],
            ['name' => 'Andorra', 'code' => 'AD', 'iso_code' => 'AND', 'phone_code' => '376'],
            ['name' => 'Angola', 'code' => 'AO', 'iso_code' => 'AGO', 'phone_code' => '244'],
            ['name' => 'Anguilla', 'code' => 'AI', 'iso_code' => 'AIA', 'phone_code' => '1264'],
            ['name' => 'Antarctica', 'code' => 'AQ', 'iso_code' => 'ATA', 'phone_code' => '672'],
            ['name' => 'Antigua and Barbuda', 'code' => 'AG', 'iso_code' => 'ATG', 'phone_code' => '1268'],
            ['name' => 'Argentina', 'code' => 'AR', 'iso_code' => 'ARG', 'phone_code' => '54'],
            ['name' => 'Armenia', 'code' => 'AM', 'iso_code' => 'ARM', 'phone_code' => '374'],
            ['name' => 'Aruba', 'code' => 'AW', 'iso_code' => 'ABW', 'phone_code' => '297'],
            ['name' => 'Australia', 'code' => 'AU', 'iso_code' => 'AUS', 'phone_code' => '61'],
            ['name' => 'Austria', 'code' => 'AT', 'iso_code' => 'AUT', 'phone_code' => '43'],
            ['name' => 'Azerbaijan', 'code' => 'AZ', 'iso_code' => 'AZE', 'phone_code' => '994'],
            ['name' => 'Bahamas', 'code' => 'BS', 'iso_code' => 'BHS', 'phone_code' => '1242'],
            ['name' => 'Bahrain', 'code' => 'BH', 'iso_code' => 'BHR', 'phone_code' => '973'],
            ['name' => 'Bangladesh', 'code' => 'BD', 'iso_code' => 'BGD', 'phone_code' => '880'],
            ['name' => 'Barbados', 'code' => 'BB', 'iso_code' => 'BRB', 'phone_code' => '1246'],
            ['name' => 'Belarus', 'code' => 'BY', 'iso_code' => 'BLR', 'phone_code' => '375'],
            ['name' => 'Belgium', 'code' => 'BE', 'iso_code' => 'BEL', 'phone_code' => '32'],
            ['name' => 'Belize', 'code' => 'BZ', 'iso_code' => 'BLZ', 'phone_code' => '501'],
            ['name' => 'Benin', 'code' => 'BJ', 'iso_code' => 'BEN', 'phone_code' => '229'],
            ['name' => 'Bermuda', 'code' => 'BM', 'iso_code' => 'BMU', 'phone_code' => '1441'],
            ['name' => 'Bhutan', 'code' => 'BT', 'iso_code' => 'BTN', 'phone_code' => '975'],
            ['name' => 'Bolivia', 'code' => 'BO', 'iso_code' => 'BOL', 'phone_code' => '591'],
            ['name' => 'Bosnia and Herzegovina', 'code' => 'BA', 'iso_code' => 'BIH', 'phone_code' => '387'],
            ['name' => 'Botswana', 'code' => 'BW', 'iso_code' => 'BWA', 'phone_code' => '267'],
            ['name' => 'Bouvet Island', 'code' => 'BV', 'iso_code' => 'BVT', 'phone_code' => '47'],
            ['name' => 'Brazil', 'code' => 'BR', 'iso_code' => 'BRA', 'phone_code' => '55'],
            ['name' => 'British Indian Ocean Territory', 'code' => 'IO', 'iso_code' => 'IOT', 'phone_code' => '246'],
            ['name' => 'Brunei Darussalam', 'code' => 'BN', 'iso_code' => 'BRN', 'phone_code' => '673'],
            ['name' => 'Bulgaria', 'code' => 'BG', 'iso_code' => 'BGR', 'phone_code' => '359'],
            ['name' => 'Burkina Faso', 'code' => 'BF', 'iso_code' => 'BFA', 'phone_code' => '226'],
            ['name' => 'Burundi', 'code' => 'BI', 'iso_code' => 'BDI', 'phone_code' => '257'],
            ['name' => 'Cambodia', 'code' => 'KH', 'iso_code' => 'KHM', 'phone_code' => '855'],
            ['name' => 'Cameroon', 'code' => 'CM', 'iso_code' => 'CMR', 'phone_code' => '237'],
            ['name' => 'Canada', 'code' => 'CA', 'iso_code' => 'CAN', 'phone_code' => '1'],
            ['name' => 'Cape Verde', 'code' => 'CV', 'iso_code' => 'CPV', 'phone_code' => '238'],
            ['name' => 'Cayman Islands', 'code' => 'KY', 'iso_code' => 'CYM', 'phone_code' => '1345'],
            ['name' => 'Central African Republic', 'code' => 'CF', 'iso_code' => 'CAF', 'phone_code' => '236'],
            ['name' => 'Chad', 'code' => 'TD', 'iso_code' => 'TCD', 'phone_code' => '235'],
            ['name' => 'Chile', 'code' => 'CL', 'iso_code' => 'CHL', 'phone_code' => '56'],
            ['name' => 'China', 'code' => 'CN', 'iso_code' => 'CHN', 'phone_code' => '86'],
            ['name' => 'Christmas Island', 'code' => 'CX', 'iso_code' => 'CXR', 'phone_code' => '61'],
            ['name' => 'Cocos (Keeling) Islands', 'code' => 'CC', 'iso_code' => 'CCK', 'phone_code' => '61'],
            ['name' => 'Colombia', 'code' => 'CO', 'iso_code' => 'COL', 'phone_code' => '57'],
            ['name' => 'Comoros', 'code' => 'KM', 'iso_code' => 'COM', 'phone_code' => '269'],
            ['name' => 'Congo', 'code' => 'CG', 'iso_code' => 'COG', 'phone_code' => '242'],
            ['name' => 'Congo, Democratic Republic', 'code' => 'CD', 'iso_code' => 'COD', 'phone_code' => '243'],
            ['name' => 'Cook Islands', 'code' => 'CK', 'iso_code' => 'COK', 'phone_code' => '682'],
            ['name' => 'Costa Rica', 'code' => 'CR', 'iso_code' => 'CRI', 'phone_code' => '506'],
            ['name' => 'Cote D\'Ivoire', 'code' => 'CI', 'iso_code' => 'CIV', 'phone_code' => '225'],
            ['name' => 'Croatia', 'code' => 'HR', 'iso_code' => 'HRV', 'phone_code' => '385'],
            ['name' => 'Cuba', 'code' => 'CU', 'iso_code' => 'CUB', 'phone_code' => '53'],
            ['name' => 'Cyprus', 'code' => 'CY', 'iso_code' => 'CYP', 'phone_code' => '357'],
            ['name' => 'Czech Republic', 'code' => 'CZ', 'iso_code' => 'CZE', 'phone_code' => '420'],
            ['name' => 'Denmark', 'code' => 'DK', 'iso_code' => 'DNK', 'phone_code' => '45'],
            ['name' => 'Djibouti', 'code' => 'DJ', 'iso_code' => 'DJI', 'phone_code' => '253'],
            ['name' => 'Dominica', 'code' => 'DM', 'iso_code' => 'DMA', 'phone_code' => '1767'],
            ['name' => 'Dominican Republic', 'code' => 'DO', 'iso_code' => 'DOM', 'phone_code' => '1809'],
            ['name' => 'Ecuador', 'code' => 'EC', 'iso_code' => 'ECU', 'phone_code' => '593'],
            ['name' => 'Egypt', 'code' => 'EG', 'iso_code' => 'EGY', 'phone_code' => '20'],
            ['name' => 'El Salvador', 'code' => 'SV', 'iso_code' => 'SLV', 'phone_code' => '503'],
            ['name' => 'Equatorial Guinea', 'code' => 'GQ', 'iso_code' => 'GNQ', 'phone_code' => '240'],
            ['name' => 'Eritrea', 'code' => 'ER', 'iso_code' => 'ERI', 'phone_code' => '291'],
            ['name' => 'Estonia', 'code' => 'EE', 'iso_code' => 'EST', 'phone_code' => '372'],
            ['name' => 'Ethiopia', 'code' => 'ET', 'iso_code' => 'ETH', 'phone_code' => '251'],
            ['name' => 'Falkland Islands (Malvinas)', 'code' => 'FK', 'iso_code' => 'FLK', 'phone_code' => '500'],
            ['name' => 'Faroe Islands', 'code' => 'FO', 'iso_code' => 'FRO', 'phone_code' => '298'],
            ['name' => 'Fiji', 'code' => 'FJ', 'iso_code' => 'FJI', 'phone_code' => '679'],
            ['name' => 'Finland', 'code' => 'FI', 'iso_code' => 'FIN', 'phone_code' => '358'],
            ['name' => 'France', 'code' => 'FR', 'iso_code' => 'FRA', 'phone_code' => '33'],
            ['name' => 'French Guiana', 'code' => 'GF', 'iso_code' => 'GUF', 'phone_code' => '594'],
            ['name' => 'French Polynesia', 'code' => 'PF', 'iso_code' => 'PYF', 'phone_code' => '689'],
            ['name' => 'French Southern Territories', 'code' => 'TF', 'iso_code' => 'ATF', 'phone_code' => '262'],
            ['name' => 'Gabon', 'code' => 'GA', 'iso_code' => 'GAB', 'phone_code' => '241'],
            ['name' => 'Gambia', 'code' => 'GM', 'iso_code' => 'GMB', 'phone_code' => '220'],
            ['name' => 'Georgia', 'code' => 'GE', 'iso_code' => 'GEO', 'phone_code' => '995'],
            ['name' => 'Germany', 'code' => 'DE', 'iso_code' => 'DEU', 'phone_code' => '49'],
            ['name' => 'Ghana', 'code' => 'GH', 'iso_code' => 'GHA', 'phone_code' => '233'],
            ['name' => 'Gibraltar', 'code' => 'GI', 'iso_code' => 'GIB', 'phone_code' => '350'],
            ['name' => 'Greece', 'code' => 'GR', 'iso_code' => 'GRC', 'phone_code' => '30'],
            ['name' => 'Greenland', 'code' => 'GL', 'iso_code' => 'GRL', 'phone_code' => '299'],
            ['name' => 'Grenada', 'code' => 'GD', 'iso_code' => 'GRD', 'phone_code' => '1473'],
            ['name' => 'Guadeloupe', 'code' => 'GP', 'iso_code' => 'GLP', 'phone_code' => '590'],
            ['name' => 'Guam', 'code' => 'GU', 'iso_code' => 'GUM', 'phone_code' => '1671'],
            ['name' => 'Guatemala', 'code' => 'GT', 'iso_code' => 'GTM', 'phone_code' => '502'],
            ['name' => 'Guernsey', 'code' => 'GG', 'iso_code' => 'GGY', 'phone_code' => '44'],
            ['name' => 'Guinea', 'code' => 'GN', 'iso_code' => 'GIN', 'phone_code' => '224'],
            ['name' => 'Guinea-Bissau', 'code' => 'GW', 'iso_code' => 'GNB', 'phone_code' => '245'],
            ['name' => 'Guyana', 'code' => 'GY', 'iso_code' => 'GUY', 'phone_code' => '592'],
            ['name' => 'Haiti', 'code' => 'HT', 'iso_code' => 'HTI', 'phone_code' => '509'],
            ['name' => 'Heard Island & Mcdonald Islands', 'code' => 'HM', 'iso_code' => 'HMD', 'phone_code' => '672'],
            ['name' => 'Holy See (Vatican City State)', 'code' => 'VA', 'iso_code' => 'VAT', 'phone_code' => '39'],
            ['name' => 'Honduras', 'code' => 'HN', 'iso_code' => 'HND', 'phone_code' => '504'],
            ['name' => 'Hong Kong', 'code' => 'HK', 'iso_code' => 'HKG', 'phone_code' => '852'],
            ['name' => 'Hungary', 'code' => 'HU', 'iso_code' => 'HUN', 'phone_code' => '36'],
            ['name' => 'Iceland', 'code' => 'IS', 'iso_code' => 'ISL', 'phone_code' => '354'],
            ['name' => 'India', 'code' => 'IN', 'iso_code' => 'IND', 'phone_code' => '91'],
            ['name' => 'Indonesia', 'code' => 'ID', 'iso_code' => 'IDN', 'phone_code' => '62'],
            ['name' => 'Iran, Islamic Republic Of', 'code' => 'IR', 'iso_code' => 'IRN', 'phone_code' => '98'],
            ['name' => 'Iraq', 'code' => 'IQ', 'iso_code' => 'IRQ', 'phone_code' => '964'],
            ['name' => 'Ireland', 'code' => 'IE', 'iso_code' => 'IRL', 'phone_code' => '353'],
            ['name' => 'Isle of Man', 'code' => 'IM', 'iso_code' => 'IMN', 'phone_code' => '44'],
            ['name' => 'Israel', 'code' => 'IL', 'iso_code' => 'ISR', 'phone_code' => '972'],
            ['name' => 'Italy', 'code' => 'IT', 'iso_code' => 'ITA', 'phone_code' => '39'],
            ['name' => 'Jamaica', 'code' => 'JM', 'iso_code' => 'JAM', 'phone_code' => '1876'],
            ['name' => 'Japan', 'code' => 'JP', 'iso_code' => 'JPN', 'phone_code' => '81'],
            ['name' => 'Jersey', 'code' => 'JE', 'iso_code' => 'JEY', 'phone_code' => '44'],
            ['name' => 'Jordan', 'code' => 'JO', 'iso_code' => 'JOR', 'phone_code' => '962'],
            ['name' => 'Kazakhstan', 'code' => 'KZ', 'iso_code' => 'KAZ', 'phone_code' => '7'],
            ['name' => 'Kenya', 'code' => 'KE', 'iso_code' => 'KEN', 'phone_code' => '254'],
            ['name' => 'Kiribati', 'code' => 'KI', 'iso_code' => 'KIR', 'phone_code' => '686'],
            ['name' => 'Korea, Democratic People\'s Republic of', 'code' => 'KP', 'iso_code' => 'PRK', 'phone_code' => '850'],
            ['name' => 'Korea, Republic of', 'code' => 'KR', 'iso_code' => 'KOR', 'phone_code' => '82'],
            ['name' => 'Kuwait', 'code' => 'KW', 'iso_code' => 'KWT', 'phone_code' => '965'],
            ['name' => 'Kyrgyzstan', 'code' => 'KG', 'iso_code' => 'KGZ', 'phone_code' => '996'],
            ['name' => 'Lao People\'s Democratic Republic', 'code' => 'LA', 'iso_code' => 'LAO', 'phone_code' => '856'],
            ['name' => 'Latvia', 'code' => 'LV', 'iso_code' => 'LVA', 'phone_code' => '371'],
            ['name' => 'Lebanon', 'code' => 'LB', 'iso_code' => 'LBN', 'phone_code' => '961'],
            ['name' => 'Lesotho', 'code' => 'LS', 'iso_code' => 'LSO', 'phone_code' => '266'],
            ['name' => 'Liberia', 'code' => 'LR', 'iso_code' => 'LBR', 'phone_code' => '231'],
            ['name' => 'Libyan Arab Jamahiriya', 'code' => 'LY', 'iso_code' => 'LBY', 'phone_code' => '218'],
            ['name' => 'Liechtenstein', 'code' => 'LI', 'iso_code' => 'LIE', 'phone_code' => '423'],
            ['name' => 'Lithuania', 'code' => 'LT', 'iso_code' => 'LTU', 'phone_code' => '370'],
            ['name' => 'Luxembourg', 'code' => 'LU', 'iso_code' => 'LUX', 'phone_code' => '352'],
            ['name' => 'Macao', 'code' => 'MO', 'iso_code' => 'MAC', 'phone_code' => '853'],
            ['name' => 'Macedonia', 'code' => 'MK', 'iso_code' => 'MKD', 'phone_code' => '389'],
            ['name' => 'Madagascar', 'code' => 'MG', 'iso_code' => 'MDG', 'phone_code' => '261'],
            ['name' => 'Malawi', 'code' => 'MW', 'iso_code' => 'MWI', 'phone_code' => '265'],
            ['name' => 'Malaysia', 'code' => 'MY', 'iso_code' => 'MYS', 'phone_code' => '60'],
            ['name' => 'Maldives', 'code' => 'MV', 'iso_code' => 'MDV', 'phone_code' => '960'],
            ['name' => 'Mali', 'code' => 'ML', 'iso_code' => 'MLI', 'phone_code' => '223'],
            ['name' => 'Malta', 'code' => 'MT', 'iso_code' => 'MLT', 'phone_code' => '356'],
            ['name' => 'Marshall Islands', 'code' => 'MH', 'iso_code' => 'MHL', 'phone_code' => '692'],
            ['name' => 'Martinique', 'code' => 'MQ', 'iso_code' => 'MTQ', 'phone_code' => '596'],
            ['name' => 'Mauritania', 'code' => 'MR', 'iso_code' => 'MRT', 'phone_code' => '222'],
            ['name' => 'Mauritius', 'code' => 'MU', 'iso_code' => 'MUS', 'phone_code' => '230'],
            ['name' => 'Mayotte', 'code' => 'YT', 'iso_code' => 'MYT', 'phone_code' => '262'],
            ['name' => 'Mexico', 'code' => 'MX', 'iso_code' => 'MEX', 'phone_code' => '52'],
            ['name' => 'Micronesia, Federated States of', 'code' => 'FM', 'iso_code' => 'FSM', 'phone_code' => '691'],
            ['name' => 'Moldova, Republic of', 'code' => 'MD', 'iso_code' => 'MDA', 'phone_code' => '373'],
            ['name' => 'Monaco', 'code' => 'MC', 'iso_code' => 'MCO', 'phone_code' => '377'],
            ['name' => 'Mongolia', 'code' => 'MN', 'iso_code' => 'MNG', 'phone_code' => '976'],
            ['name' => 'Montenegro', 'code' => 'ME', 'iso_code' => 'MNE', 'phone_code' => '382'],
            ['name' => 'Montserrat', 'code' => 'MS', 'iso_code' => 'MSR', 'phone_code' => '1664'],
            ['name' => 'Morocco', 'code' => 'MA', 'iso_code' => 'MAR', 'phone_code' => '212'],
            ['name' => 'Mozambique', 'code' => 'MZ', 'iso_code' => 'MOZ', 'phone_code' => '258'],
            ['name' => 'Myanmar', 'code' => 'MM', 'iso_code' => 'MMR', 'phone_code' => '95'],
            ['name' => 'Namibia', 'code' => 'NA', 'iso_code' => 'NAM', 'phone_code' => '264'],
            ['name' => 'Nauru', 'code' => 'NR', 'iso_code' => 'NRU', 'phone_code' => '674'],
            ['name' => 'Nepal', 'code' => 'NP', 'iso_code' => 'NPL', 'phone_code' => '977'],
            ['name' => 'Netherlands', 'code' => 'NL', 'iso_code' => 'NLD', 'phone_code' => '31'],
            ['name' => 'Netherlands Antilles', 'code' => 'AN', 'iso_code' => 'ANT', 'phone_code' => '599'],
            ['name' => 'New Caledonia', 'code' => 'NC', 'iso_code' => 'NCL', 'phone_code' => '687'],
            ['name' => 'New Zealand', 'code' => 'NZ', 'iso_code' => 'NZL', 'phone_code' => '64'],
            ['name' => 'Nicaragua', 'code' => 'NI', 'iso_code' => 'NIC', 'phone_code' => '505'],
            ['name' => 'Niger', 'code' => 'NE', 'iso_code' => 'NER', 'phone_code' => '227'],
            ['name' => 'Nigeria', 'code' => 'NG', 'iso_code' => 'NGA', 'phone_code' => '234'],
            ['name' => 'Niue', 'code' => 'NU', 'iso_code' => 'NIU', 'phone_code' => '683'],
            ['name' => 'Norfolk Island', 'code' => 'NF', 'iso_code' => 'NFK', 'phone_code' => '672'],
            ['name' => 'Northern Mariana Islands', 'code' => 'MP', 'iso_code' => 'MNP', 'phone_code' => '1670'],
            ['name' => 'Norway', 'code' => 'NO', 'iso_code' => 'NOR', 'phone_code' => '47'],
            ['name' => 'Oman', 'code' => 'OM', 'iso_code' => 'OMN', 'phone_code' => '968'],
            ['name' => 'Pakistan', 'code' => 'PK', 'iso_code' => 'PAK', 'phone_code' => '92'],
            ['name' => 'Palau', 'code' => 'PW', 'iso_code' => 'PLW', 'phone_code' => '680'],
            ['name' => 'Palestinian Territory, Occupied', 'code' => 'PS', 'iso_code' => 'PSE', 'phone_code' => '970'],
            ['name' => 'Panama', 'code' => 'PA', 'iso_code' => 'PAN', 'phone_code' => '507'],
            ['name' => 'Papua New Guinea', 'code' => 'PG', 'iso_code' => 'PNG', 'phone_code' => '675'],
            ['name' => 'Paraguay', 'code' => 'PY', 'iso_code' => 'PRY', 'phone_code' => '595'],
            ['name' => 'Peru', 'code' => 'PE', 'iso_code' => 'PER', 'phone_code' => '51'],
            ['name' => 'Philippines', 'code' => 'PH', 'iso_code' => 'PHL', 'phone_code' => '63'],
            ['name' => 'Pitcairn', 'code' => 'PN', 'iso_code' => 'PCN', 'phone_code' => '870'],
            ['name' => 'Poland', 'code' => 'PL', 'iso_code' => 'POL', 'phone_code' => '48'],
            ['name' => 'Portugal', 'code' => 'PT', 'iso_code' => 'PRT', 'phone_code' => '351'],
            ['name' => 'Puerto Rico', 'code' => 'PR', 'iso_code' => 'PRI', 'phone_code' => '1'],
            ['name' => 'Qatar', 'code' => 'QA', 'iso_code' => 'QAT', 'phone_code' => '974'],
            ['name' => 'Reunion', 'code' => 'RE', 'iso_code' => 'REU', 'phone_code' => '262'],
            ['name' => 'Romania', 'code' => 'RO', 'iso_code' => 'ROU', 'phone_code' => '40'],
            ['name' => 'Russian Federation', 'code' => 'RU', 'iso_code' => 'RUS', 'phone_code' => '7'],
            ['name' => 'Rwanda', 'code' => 'RW', 'iso_code' => 'RWA', 'phone_code' => '250'],
            ['name' => 'Saint Barthelemy', 'code' => 'BL', 'iso_code' => 'BLM', 'phone_code' => '590'],
            ['name' => 'Saint Helena', 'code' => 'SH', 'iso_code' => 'SHN', 'phone_code' => '290'],
            ['name' => 'Saint Kitts and Nevis', 'code' => 'KN', 'iso_code' => 'KNA', 'phone_code' => '1869'],
            ['name' => 'Saint Lucia', 'code' => 'LC', 'iso_code' => 'LCA', 'phone_code' => '1758'],
            ['name' => 'Saint Martin', 'code' => 'MF', 'iso_code' => 'MAF', 'phone_code' => '590'],
            ['name' => 'Saint Pierre and Miquelon', 'code' => 'PM', 'iso_code' => 'SPM', 'phone_code' => '508'],
            ['name' => 'Saint Vincent and the Grenadines', 'code' => 'VC', 'iso_code' => 'VCT', 'phone_code' => '1784'],
            ['name' => 'Samoa', 'code' => 'WS', 'iso_code' => 'WSM', 'phone_code' => '685'],
            ['name' => 'San Marino', 'code' => 'SM', 'iso_code' => 'SMR', 'phone_code' => '378'],
            ['name' => 'Sao Tome and Principe', 'code' => 'ST', 'iso_code' => 'STP', 'phone_code' => '239'],
            ['name' => 'Saudi Arabia', 'code' => 'SA', 'iso_code' => 'SAU', 'phone_code' => '966'],
            ['name' => 'Senegal', 'code' => 'SN', 'iso_code' => 'SEN', 'phone_code' => '221'],
            ['name' => 'Serbia', 'code' => 'RS', 'iso_code' => 'SRB', 'phone_code' => '381'],
            ['name' => 'Seychelles', 'code' => 'SC', 'iso_code' => 'SYC', 'phone_code' => '248'],
            ['name' => 'Sierra Leone', 'code' => 'SL', 'iso_code' => 'SLE', 'phone_code' => '232'],
            ['name' => 'Singapore', 'code' => 'SG', 'iso_code' => 'SGP', 'phone_code' => '65'],
            ['name' => 'Slovakia', 'code' => 'SK', 'iso_code' => 'SVK', 'phone_code' => '421'],
            ['name' => 'Slovenia', 'code' => 'SI', 'iso_code' => 'SVN', 'phone_code' => '386'],
            ['name' => 'Solomon Islands', 'code' => 'SB', 'iso_code' => 'SLB', 'phone_code' => '677'],
            ['name' => 'Somalia', 'code' => 'SO', 'iso_code' => 'SOM', 'phone_code' => '252'],
            ['name' => 'South Africa', 'code' => 'ZA', 'iso_code' => 'ZAF', 'phone_code' => '27'],
            ['name' => 'South Georgia and the South Sandwich Islands', 'code' => 'GS', 'iso_code' => 'SGS', 'phone_code' => '500'],
            ['name' => 'Spain', 'code' => 'ES', 'iso_code' => 'ESP', 'phone_code' => '34'],
            ['name' => 'Sri Lanka', 'code' => 'LK', 'iso_code' => 'LKA', 'phone_code' => '94'],
            ['name' => 'Sudan', 'code' => 'SD', 'iso_code' => 'SDN', 'phone_code' => '249'],
            ['name' => 'Suriname', 'code' => 'SR', 'iso_code' => 'SUR', 'phone_code' => '597'],
            ['name' => 'Svalbard and Jan Mayen', 'code' => 'SJ', 'iso_code' => 'SJM', 'phone_code' => '47'],
            ['name' => 'Swaziland', 'code' => 'SZ', 'iso_code' => 'SWZ', 'phone_code' => '268'],
            ['name' => 'Sweden', 'code' => 'SE', 'iso_code' => 'SWE', 'phone_code' => '46'],
            ['name' => 'Switzerland', 'code' => 'CH', 'iso_code' => 'CHE', 'phone_code' => '41'],
            ['name' => 'Syrian Arab Republic', 'code' => 'SY', 'iso_code' => 'SYR', 'phone_code' => '963'],
            ['name' => 'Taiwan', 'code' => 'TW', 'iso_code' => 'TWN', 'phone_code' => '886'],
            ['name' => 'Tajikistan', 'code' => 'TJ', 'iso_code' => 'TJK', 'phone_code' => '992'],
            ['name' => 'Tanzania, United Republic of', 'code' => 'TZ', 'iso_code' => 'TZA', 'phone_code' => '255'],
            ['name' => 'Thailand', 'code' => 'TH', 'iso_code' => 'THA', 'phone_code' => '66'],
            ['name' => 'Timor-Leste', 'code' => 'TL', 'iso_code' => 'TLS', 'phone_code' => '670'],
            ['name' => 'Togo', 'code' => 'TG', 'iso_code' => 'TGO', 'phone_code' => '228'],
            ['name' => 'Tokelau', 'code' => 'TK', 'iso_code' => 'TKL', 'phone_code' => '690'],
            ['name' => 'Tonga', 'code' => 'TO', 'iso_code' => 'TON', 'phone_code' => '676'],
            ['name' => 'Trinidad and Tobago', 'code' => 'TT', 'iso_code' => 'TTO', 'phone_code' => '1868'],
            ['name' => 'Tunisia', 'code' => 'TN', 'iso_code' => 'TUN', 'phone_code' => '216'],
            ['name' => 'Turkey', 'code' => 'TR', 'iso_code' => 'TUR', 'phone_code' => '90'],
            ['name' => 'Turkmenistan', 'code' => 'TM', 'iso_code' => 'TKM', 'phone_code' => '993'],
            ['name' => 'Turks and Caicos Islands', 'code' => 'TC', 'iso_code' => 'TCA', 'phone_code' => '1649'],
            ['name' => 'Tuvalu', 'code' => 'TV', 'iso_code' => 'TUV', 'phone_code' => '688'],
            ['name' => 'Uganda', 'code' => 'UG', 'iso_code' => 'UGA', 'phone_code' => '256'],
            ['name' => 'Ukraine', 'code' => 'UA', 'iso_code' => 'UKR', 'phone_code' => '380'],
            ['name' => 'United Arab Emirates', 'code' => 'AE', 'iso_code' => 'ARE', 'phone_code' => '971'],
            ['name' => 'United Kingdom', 'code' => 'GB', 'iso_code' => 'GBR', 'phone_code' => '44'],
            ['name' => 'United States', 'code' => 'US', 'iso_code' => 'USA', 'phone_code' => '1'],
            ['name' => 'United States Minor Outlying Islands', 'code' => 'UM', 'iso_code' => 'UMI', 'phone_code' => '1'],
            ['name' => 'Uruguay', 'code' => 'UY', 'iso_code' => 'URY', 'phone_code' => '598'],
            ['name' => 'Uzbekistan', 'code' => 'UZ', 'iso_code' => 'UZB', 'phone_code' => '998'],
            ['name' => 'Vanuatu', 'code' => 'VU', 'iso_code' => 'VUT', 'phone_code' => '678'],
            ['name' => 'Venezuela', 'code' => 'VE', 'iso_code' => 'VEN', 'phone_code' => '58'],
            ['name' => 'Viet Nam', 'code' => 'VN', 'iso_code' => 'VNM', 'phone_code' => '84'],
            ['name' => 'Virgin Islands, British', 'code' => 'VG', 'iso_code' => 'VGB', 'phone_code' => '1284'],
            ['name' => 'Virgin Islands, U.S.', 'code' => 'VI', 'iso_code' => 'VIR', 'phone_code' => '1340'],
            ['name' => 'Wallis and Futuna', 'code' => 'WF', 'iso_code' => 'WLF', 'phone_code' => '681'],
            ['name' => 'Western Sahara', 'code' => 'EH', 'iso_code' => 'ESH', 'phone_code' => '212'],
            ['name' => 'Yemen', 'code' => 'YE', 'iso_code' => 'YEM', 'phone_code' => '967'],
            ['name' => 'Zambia', 'code' => 'ZM', 'iso_code' => 'ZMB', 'phone_code' => '260'],
            ['name' => 'Zimbabwe', 'code' => 'ZW', 'iso_code' => 'ZWE', 'phone_code' => '263'],
        ];

        foreach ($countries as $country) {
            Country::updateOrCreate(
                ['code' => $country['code']], // Check by code to avoid duplicates
                $country
            );
        }

        $this->command->info('Countries seeded successfully!');
    }
}